### ISSUE TITLE
Cropped Text Error

### ISSUE THREAD

**Issue by kinifwyne** [jmattheis/gruvbox-dark-gtk#1]
In the GTKWave application, some text boxes become unreadable. Here is a comparison of the Raleigh theme with the gruvbox-dark-gtk:

![error](https://user-images.githubusercontent.com/23533194/115940507-5f3d5400-a491-11eb-9706-dfd240e398b2.png)

I did install the Oomix program, imported the oomox-color-file, and exported the theme, and the problem was fixed.

```
               +                OS: Arch Linux x86_64
               #                Hostname: zyrock
              ###               Kernel Release: 5.11.15-arch1-2
             #####              Uptime: 7:10
             ######             WM: i3
            ; #####;            DE: None
           +##.#####            Packages: 817
          +##########           RAM: 1636 MB / 15787 MB
         #############;         Processor Type: Intel(R) Core(TM) i5-9400H CPU @ 2.50GHz
        ###############+        $EDITOR: vim
       #######   #######        Root: 138G / 251G (54%) (ext4)
     .######;     ;###;`".
    .#######;     ;#####.
    #########.   .########`
   ######'           '######
  ;####                 ####;
  ##'                     '##
 #'                         `#
```

**Comment by jmattheis** [comment]
Hey, thanks for your issue, I can reproduce this bug, but I can't fix it by re-exporting the theme, would you like to open a pullrequest with your exported theme?

**Comment by kinifwyne** [comment]
I just created a pull request. All I did was import the oomox-color-file from the master branch of the project, and export it. I did modify a comment in the index.theme that was produced. The export added many files.

**Comment by jmattheis** [comment]
Thanks, I've updated the package inside the aur https://aur.archlinux.org/packages/gruvbox-dark-gtk
